# Supabase connection
SUPABASE_URL = "https://oudjcqhyldpncjbxohsg.supabase.co"
SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZGpjcWh5bGRwbmNqYnhvaHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDgyNDQsImV4cCI6MjA3MDg4NDI0NH0.SYwTtCe3r7WOZ25CRggL-lBkvGPjKnQhY_dT4Kjv9Dg"

# App settings
APP_TZ = "America/Toronto"

# Hugging Face
HF_TOKEN = "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"

# Optional VLM model provider
PROVIDER = "nebius"
GEMMA_MODEL = "google/gemma-3-27b-it"
NEBIUS_API_KEY = "eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMjk4MzMxNjQ1OTQzNjA5ODYxMyIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkxNTEzMTE3MiwidXVpZCI6IjJmOTUxZmM1LWEyNTgtNDg5OC1iNWI4LTkwZTljY2RkZjU2NSIsIm5hbWUiOiJjYXJlIGNvdW50IGFwcCIsImV4cGlyZXNfYXQiOiIyMDMwLTA5LTA4VDIwOjUyOjUyKzAwMDAifQ.awAHOieD93pCnYmFMgRQ64-i6yZdO0XvXczD4eS6xEI"
NEBIUS_BASE_URL = "https://api.nebius.ai/v1"